pipeline:
  name: JavaPipeline
  identifier: JavaPipeline
  projectIdentifier: FM_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        repoName: neobank
        build: <+input>
  stages:
    - stage:
        name: BuildJava
        identifier: BuildJava
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: fmk8s
              namespace: buildfactory
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    connectorRef: dockerhubfrancislabs
                    image: maven
                    shell: Sh
                    command: |+
                      cat pom.xml
                      #mvn -Dmaven.test.skip=true -f pom.xml clean install -X

          sharedPaths:
            - /root/.m2
            - /var/run
            - /opt
          caching:
            enabled: false
            paths: []
